/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: payload.proto */

#ifndef PROTOBUF_C_payload_2eproto__INCLUDED
#define PROTOBUF_C_payload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SERVERHELLO SERVERHELLO;
typedef struct _Payload Payload;


/* --- enums --- */

typedef enum _MessageType {
  MESSAGE_TYPE__MSG_TYPE_SERVER_HELLO = 0,
  MESSAGE_TYPE__MSG_TYPE_CLIENT_HELLO = 1,
  MESSAGE_TYPE__MSG_TYPE_USER_LIST = 3,
  MESSAGE_TYPE__MSG_TYPE_RELAY_MESSSAGE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESSAGE_TYPE)
} MessageType;

/* --- messages --- */

struct  _SERVERHELLO
{
  ProtobufCMessage base;
  int32_t port;
  char *ip;
};
#define SERVERHELLO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&serverhello__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _Payload
{
  ProtobufCMessage base;
  MessageType mtype;
  SERVERHELLO *serverhello;
};
#define PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&payload__descriptor) \
    , MESSAGE_TYPE__MSG_TYPE_SERVER_HELLO, NULL }


/* SERVERHELLO methods */
void   serverhello__init
                     (SERVERHELLO         *message);
size_t serverhello__get_packed_size
                     (const SERVERHELLO   *message);
size_t serverhello__pack
                     (const SERVERHELLO   *message,
                      uint8_t             *out);
size_t serverhello__pack_to_buffer
                     (const SERVERHELLO   *message,
                      ProtobufCBuffer     *buffer);
SERVERHELLO *
       serverhello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   serverhello__free_unpacked
                     (SERVERHELLO *message,
                      ProtobufCAllocator *allocator);
/* Payload methods */
void   payload__init
                     (Payload         *message);
size_t payload__get_packed_size
                     (const Payload   *message);
size_t payload__pack
                     (const Payload   *message,
                      uint8_t             *out);
size_t payload__pack_to_buffer
                     (const Payload   *message,
                      ProtobufCBuffer     *buffer);
Payload *
       payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   payload__free_unpacked
                     (Payload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SERVERHELLO_Closure)
                 (const SERVERHELLO *message,
                  void *closure_data);
typedef void (*Payload_Closure)
                 (const Payload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    message_type__descriptor;
extern const ProtobufCMessageDescriptor serverhello__descriptor;
extern const ProtobufCMessageDescriptor payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_payload_2eproto__INCLUDED */
