/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: payload.proto */

#ifndef PROTOBUF_C_payload_2eproto__INCLUDED
#define PROTOBUF_C_payload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _IRCMessage IRCMessage;
typedef struct _IRCPayload IRCPayload;
typedef struct _UserConfig UserConfig;


/* --- enums --- */

typedef enum _MessageType {
  MESSAGE_TYPE__userlist = 0,
  MESSAGE_TYPE__relaymessage = 1,
  MESSAGE_TYPE__clienthello = 2,
  MESSAGE_TYPE__serverhello = 3,
  MESSAGE_TYPE__keyexchange = 4,
  MESSAGE_TYPE__handshakedone = 5,
  MESSAGE_TYPE__unknownstage = 6,
  MESSAGE_TYPE__auth = 7,
  MESSAGE_TYPE__signup = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESSAGE_TYPE)
} MessageType;

/* --- messages --- */

struct  _IRCMessage
{
  ProtobufCMessage base;
  char *key;
  int32_t authstatus;
  UserConfig *userconfig;
};
#define IRCMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ircmessage__descriptor) \
    , (char *)protobuf_c_empty_string, 0, NULL }


struct  _IRCPayload
{
  ProtobufCMessage base;
  IRCMessage *data;
  MessageType mtype;
};
#define IRCPAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ircpayload__descriptor) \
    , NULL, MESSAGE_TYPE__userlist }


struct  _UserConfig
{
  ProtobufCMessage base;
  char *id;
  char *password;
};
#define USER_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&user_config__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* IRCMessage methods */
void   ircmessage__init
                     (IRCMessage         *message);
size_t ircmessage__get_packed_size
                     (const IRCMessage   *message);
size_t ircmessage__pack
                     (const IRCMessage   *message,
                      uint8_t             *out);
size_t ircmessage__pack_to_buffer
                     (const IRCMessage   *message,
                      ProtobufCBuffer     *buffer);
IRCMessage *
       ircmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ircmessage__free_unpacked
                     (IRCMessage *message,
                      ProtobufCAllocator *allocator);
/* IRCPayload methods */
void   ircpayload__init
                     (IRCPayload         *message);
size_t ircpayload__get_packed_size
                     (const IRCPayload   *message);
size_t ircpayload__pack
                     (const IRCPayload   *message,
                      uint8_t             *out);
size_t ircpayload__pack_to_buffer
                     (const IRCPayload   *message,
                      ProtobufCBuffer     *buffer);
IRCPayload *
       ircpayload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ircpayload__free_unpacked
                     (IRCPayload *message,
                      ProtobufCAllocator *allocator);
/* UserConfig methods */
void   user_config__init
                     (UserConfig         *message);
size_t user_config__get_packed_size
                     (const UserConfig   *message);
size_t user_config__pack
                     (const UserConfig   *message,
                      uint8_t             *out);
size_t user_config__pack_to_buffer
                     (const UserConfig   *message,
                      ProtobufCBuffer     *buffer);
UserConfig *
       user_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   user_config__free_unpacked
                     (UserConfig *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IRCMessage_Closure)
                 (const IRCMessage *message,
                  void *closure_data);
typedef void (*IRCPayload_Closure)
                 (const IRCPayload *message,
                  void *closure_data);
typedef void (*UserConfig_Closure)
                 (const UserConfig *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    message_type__descriptor;
extern const ProtobufCMessageDescriptor ircmessage__descriptor;
extern const ProtobufCMessageDescriptor ircpayload__descriptor;
extern const ProtobufCMessageDescriptor user_config__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_payload_2eproto__INCLUDED */
