/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: payload.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "payload.pb-c.h"
void   ircmessage__init
                     (IRCMessage         *message)
{
  static const IRCMessage init_value = IRCMESSAGE__INIT;
  *message = init_value;
}
size_t ircmessage__get_packed_size
                     (const IRCMessage *message)
{
  assert(message->base.descriptor == &ircmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ircmessage__pack
                     (const IRCMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ircmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ircmessage__pack_to_buffer
                     (const IRCMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ircmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IRCMessage *
       ircmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IRCMessage *)
     protobuf_c_message_unpack (&ircmessage__descriptor,
                                allocator, len, data);
}
void   ircmessage__free_unpacked
                     (IRCMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ircmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ircpayload__init
                     (IRCPayload         *message)
{
  static const IRCPayload init_value = IRCPAYLOAD__INIT;
  *message = init_value;
}
size_t ircpayload__get_packed_size
                     (const IRCPayload *message)
{
  assert(message->base.descriptor == &ircpayload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ircpayload__pack
                     (const IRCPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ircpayload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ircpayload__pack_to_buffer
                     (const IRCPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ircpayload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IRCPayload *
       ircpayload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IRCPayload *)
     protobuf_c_message_unpack (&ircpayload__descriptor,
                                allocator, len, data);
}
void   ircpayload__free_unpacked
                     (IRCPayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ircpayload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ircmessage__field_descriptors[2] =
{
  {
    "dfhkey",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IRCMessage, dfhkey),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "len",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IRCMessage, len),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ircmessage__field_indices_by_name[] = {
  0,   /* field[0] = dfhkey */
  1,   /* field[1] = len */
};
static const ProtobufCIntRange ircmessage__number_ranges[2 + 1] =
{
  { 3, 0 },
  { 5, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ircmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IRCMessage",
  "IRCMessage",
  "IRCMessage",
  "",
  sizeof(IRCMessage),
  2,
  ircmessage__field_descriptors,
  ircmessage__field_indices_by_name,
  2,  ircmessage__number_ranges,
  (ProtobufCMessageInit) ircmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ircpayload__field_descriptors[2] =
{
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(IRCPayload, data),
    &ircmessage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtype",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IRCPayload, mtype),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ircpayload__field_indices_by_name[] = {
  0,   /* field[0] = data */
  1,   /* field[1] = mtype */
};
static const ProtobufCIntRange ircpayload__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ircpayload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IRCPayload",
  "IRCPayload",
  "IRCPayload",
  "",
  sizeof(IRCPayload),
  2,
  ircpayload__field_descriptors,
  ircpayload__field_indices_by_name,
  1,  ircpayload__number_ranges,
  (ProtobufCMessageInit) ircpayload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[4] =
{
  { "serverhello", "MESSAGE_TYPE__serverhello", 0 },
  { "clienthello", "MESSAGE_TYPE__clienthello", 1 },
  { "relaymessage", "MESSAGE_TYPE__relaymessage", 2 },
  { "userlist", "MESSAGE_TYPE__userlist", 3 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[4] =
{
  { "clienthello", 1 },
  { "relaymessage", 2 },
  { "serverhello", 0 },
  { "userlist", 3 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  4,
  message_type__enum_values_by_number,
  4,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
