/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: payload.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "payload.pb-c.h"
void   serverhello__init
                     (SERVERHELLO         *message)
{
  static const SERVERHELLO init_value = SERVERHELLO__INIT;
  *message = init_value;
}
size_t serverhello__get_packed_size
                     (const SERVERHELLO *message)
{
  assert(message->base.descriptor == &serverhello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t serverhello__pack
                     (const SERVERHELLO *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &serverhello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t serverhello__pack_to_buffer
                     (const SERVERHELLO *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &serverhello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SERVERHELLO *
       serverhello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SERVERHELLO *)
     protobuf_c_message_unpack (&serverhello__descriptor,
                                allocator, len, data);
}
void   serverhello__free_unpacked
                     (SERVERHELLO *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &serverhello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload__init
                     (Payload         *message)
{
  static const Payload init_value = PAYLOAD__INIT;
  *message = init_value;
}
size_t payload__get_packed_size
                     (const Payload *message)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload__pack
                     (const Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload__pack_to_buffer
                     (const Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Payload *
       payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Payload *)
     protobuf_c_message_unpack (&payload__descriptor,
                                allocator, len, data);
}
void   payload__free_unpacked
                     (Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor serverhello__field_descriptors[2] =
{
  {
    "PORT",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SERVERHELLO, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SERVERHELLO, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned serverhello__field_indices_by_name[] = {
  0,   /* field[0] = PORT */
  1,   /* field[1] = ip */
};
static const ProtobufCIntRange serverhello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor serverhello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SERVERHELLO",
  "SERVERHELLO",
  "SERVERHELLO",
  "",
  sizeof(SERVERHELLO),
  2,
  serverhello__field_descriptors,
  serverhello__field_indices_by_name,
  1,  serverhello__number_ranges,
  (ProtobufCMessageInit) serverhello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload__field_descriptors[2] =
{
  {
    "mtype",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Payload, mtype),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverhello",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Payload, serverhello),
    &serverhello__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload__field_indices_by_name[] = {
  0,   /* field[0] = mtype */
  1,   /* field[1] = serverhello */
};
static const ProtobufCIntRange payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Payload",
  "Payload",
  "Payload",
  "",
  sizeof(Payload),
  2,
  payload__field_descriptors,
  payload__field_indices_by_name,
  1,  payload__number_ranges,
  (ProtobufCMessageInit) payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[4] =
{
  { "MSG_TYPE_SERVER_HELLO", "MESSAGE_TYPE__MSG_TYPE_SERVER_HELLO", 0 },
  { "MSG_TYPE_CLIENT_HELLO", "MESSAGE_TYPE__MSG_TYPE_CLIENT_HELLO", 1 },
  { "MSG_TYPE_RELAY_MESSSAGE", "MESSAGE_TYPE__MSG_TYPE_RELAY_MESSSAGE", 2 },
  { "MSG_TYPE_USER_LIST", "MESSAGE_TYPE__MSG_TYPE_USER_LIST", 3 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[4] =
{
  { "MSG_TYPE_CLIENT_HELLO", 1 },
  { "MSG_TYPE_RELAY_MESSSAGE", 2 },
  { "MSG_TYPE_SERVER_HELLO", 0 },
  { "MSG_TYPE_USER_LIST", 3 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  4,
  message_type__enum_values_by_number,
  4,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
